### ISSUE TITLE
hello, i used your tutorial on youtube(https://www.youtube.com/watch?v=_mnEzX-IJzs), to try and run this, but im getting this error:

### ISSUE THREAD

**Issue by MaxFreeman-enterprise** [salar-dev/Facebook-chatbot-python#1]
hello, i used your tutorial on youtube(https://www.youtube.com/watch?v=_mnEzX-IJzs), to try and run this, but i'm getting this error:

Logging in "my mail"
Attempt #1 failed, retrying
Traceback (most recent call last):
  File "C:\Users\folder1\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_client.py", line 205, in login
    self._state = State.login(
  File "C:\Users\folder1\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_state.py", line 151, in login
    return cls.from_session(session=session)
  File "C:\Users\folder1\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_state.py", line 190, in from_session
    revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])
IndexError: list index out of range

please let me know what to do to fix it.

thank you in advance.

**Comment by rymaralvero** [comment]
Same Error

**Comment by salman8088-dev** [comment]
same issue
